version: 0.0
os: linux

files:
  - source:  /
    destination: /home/ubuntu/flag-app-back/
    overwrite: yes
file_exists_behavior: OVERWRITE

permissions:
  - object: /
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: /opt/codedeploy-agent/deployment-root/3ed21cfb-e328-4bcf-945e-c909b9ca3646/d-DGMDRV8C0/deployment-archive/scripts/stop.sh
      timeout: 60
  ApplicationStart:
    - location: /opt/codedeploy-agent/deployment-root/3ed21cfb-e328-4bcf-945e-c909b9ca3646/d-DGMDRV8C0/deployment-archive/scripts/start.sh
      timeout: 60
